import type { Service } from './types';

export const STATIC_SERVICES: Service[] = [
  { id: 's1',  category: 'PPF',     name: 'Llumar Gloss',       brand: 'Llumar',   price: 145000, duration: 480, warranty: '5 Year',  description: 'Premium self-healing PPF — ultra-clear, gloss-enhancing, scratch resistant', popular: false, active: true, order: 1, createdAt: null as any },
  { id: 's2',  category: 'PPF',     name: 'Llumar Platinum',    brand: 'Llumar',   price: 205000, duration: 480, warranty: '10 Year', description: 'Professional-grade platinum protection. Maximum clarity with decade-long cover', popular: true,  active: true, order: 2, createdAt: null as any },
  { id: 's3',  category: 'PPF',     name: 'Llumar Valor',       brand: 'Llumar',   price: 220000, duration: 480, warranty: '12 Year', description: 'Top-tier Valor film — the last PPF your car will ever need', popular: false, active: true, order: 3, createdAt: null as any },
  { id: 's4',  category: 'Washing', name: 'Regular Wash',       brand: null,       price: 500,    duration: 45,  warranty: null,      description: 'Thorough exterior wash, rinse and dry with chamois finish', popular: false, active: true, order: 1, createdAt: null as any },
  { id: 's5',  category: 'Washing', name: 'Premium Wash',       brand: null,       price: 1000,   duration: 60,  warranty: null,      description: 'Deep clean exterior + interior wipe-down, vacuum and tyre dressing', popular: true,  active: true, order: 2, createdAt: null as any },
  { id: 's6',  category: 'Washing', name: 'Detail SPA',         brand: null,       price: 2500,   duration: 90,  warranty: null,      description: 'Full detail spa — clay bar, foam cannon, interior steam, tyre dressing', popular: true,  active: true, order: 3, createdAt: null as any },
  { id: 's7',  category: 'Washing', name: 'Dry Clean',          brand: null,       price: 4000,   duration: 120, warranty: null,      description: 'Complete dry cleaning of all interior fabrics and surfaces', popular: false, active: true, order: 4, createdAt: null as any },
  { id: 's8',  category: 'Washing', name: 'Roof Cleaning',      brand: null,       price: 800,    duration: 30,  warranty: null,      description: 'Specialised roof lining and exterior roof surface clean', popular: false, active: true, order: 5, createdAt: null as any },
  { id: 's9',  category: 'Washing', name: 'Headlight Buffing',  brand: null,       price: 400,    duration: 20,  warranty: null,      description: 'Restoration and UV sealing per headlight unit', popular: false, active: true, order: 6, createdAt: null as any },
  { id: 's10', category: 'Ceramic', name: 'Kovalent Prolong',   brand: 'Kovalent', price: 10000,  duration: 480, warranty: '2 Year',  description: 'Entry ceramic coat — hardness, hydrophobic effect and UV shield', popular: false, active: true, order: 1, createdAt: null as any },
  { id: 's11', category: 'Ceramic', name: 'Kovalent Graphene',  brand: 'Kovalent', price: 12000,  duration: 480, warranty: '3 Year',  description: 'Graphene-infused ceramic — superior heat dissipation and lasting hydrophobics', popular: true,  active: true, order: 2, createdAt: null as any },
  { id: 's12', category: 'Ceramic', name: 'Kovalent Borophene', brand: 'Kovalent', price: 14000,  duration: 480, warranty: '5 Year',  description: 'Borophene ceramic — hardest known molecular layer, 5-year coverage', popular: true,  active: true, order: 3, createdAt: null as any },
  { id: 's13', category: 'Coating', name: 'Teflon Coating',     brand: null,       price: 5000,   duration: 120, warranty: '6 Month', description: 'Teflon layer for minor scratch resistance and paint preservation', popular: false, active: true, order: 1, createdAt: null as any },
  { id: 's14', category: 'Coating', name: 'Glass Coating',      brand: null,       price: 1200,   duration: 60,  warranty: '3 Month', description: 'Crystal-clear glass coating for all windows and windshield', popular: false, active: true, order: 2, createdAt: null as any },
  { id: 's15', category: 'Coating', name: 'Maintenance Coat',   brand: null,       price: 4500,   duration: 90,  warranty: '1 Year',  description: 'Annual refresh — reinforces existing protection, adds new hydrophobic layer', popular: true,  active: true, order: 3, createdAt: null as any },
];